version: 2
# This is a basic configuration file for Dependabot to update the git submodule
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"