[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "wt_vehicle_extractor_sgambe33"
version = "0.0.1"
authors = [
  { name="Sgambe33", email="studente.cosimo.sgambelluri@gmail.com" },
]
description = "Python package to extract vehicle data from WT datamine"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Sgambe33/WT-Vehicle-Data-Extract"
Issues = "https://github.com/Sgambe33/WT-Vehicle-Data-Extract/issues"