name: Run Main Script

on: 
  pull_request:
    branches: [master]

env:
  XATA_API_KEY: ${{ secrets.XATA_API_KEY }}
  XATA_USER: ${{ secrets.XATA_USER }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  approve-dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'Sgambe33/WT_Database'
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}


  sync-datamine:
    name: Synchronize Datamine repository
    runs-on: ubuntu-latest
    needs: approve-dependabot

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
      - name: Commit update
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"

  parse-data:
    name: Parse data
    runs-on: ubuntu-latest
    needs: sync-datamine

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Specify the Python version you need
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run main script
      run: |
        python main.py

    - name: Commit changes
      run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Updated assets and vehicle index" && git push || echo "No changes to commit"
